---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "vcf2maf"
## TODO nf-core: Add a description of the module and list keywords
description: Module to employ use of vcf2maf.pl to convert input VCF with tumor/normal columns to MAF and add respective annotations.
keywords:
  - vcf
  - maf
  - convert
  - annotate
  - perl
tools:
  - "vcf2maf":
      description: "Convert a VCF into a MAF where each variant is annotated to only one of all possible gene isoforms"
      homepage: "https://github.com/msk-access/vcf2maf"
      documentation: "https://github.com/msk-access/vcf2maf/blob/master/README.md"
      licence: ["Apache-2.0"]

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1.sample2', control_id:sample1, case_id:sample2 ]`

  - vcf:
      type: file
      description: Input VCF file with tumor and normal columns
      pattern: "*.{vcf}"

  - ref_fasta:
      type: file
      description: Input reference fasta file
      pattern: "*.{fasta}"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1.sample2', control_id:sample1, case_id:sample2 ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - maf:
      type: file
      description: Output MAF file
      pattern: "*.{maf}"

authors:
  - "@rnaidu"
maintainers:
  - "@rnaidu"
