exclude:
  - path: modules/msk/nf-test
  - profile: conda
    path: modules/msk/calculatenoise
  - profile: conda
    path: modules/msk/gbcms
  - profile: conda
    path: modules/msk/polysolver
  - profile: conda
    path: modules/msk/snppileup
  - profile: conda
    path: modules/msk/facets
  - profile: conda
    path: modules/msk/mutect1
  - profile: conda
    path: modules/msk/phylowgs/createinput
  - profile: conda
    path: modules/msk/phylowgs/parsecnvs
  - profile: conda
    path: modules/msk/phylowgs/multievolve
  - profile: conda
    path: modules/msk/phylowgs/writeresults
  - profile: conda
    path: modules/msk/netmhcpan4
  - profile: conda
    path: modules/msk/neoantigeninput
  - profile: conda
    path: modules/msk/neoantigenediting/aligntoIEDB
  - profile: conda
    path: modules/msk/neoantigenediting/computeFitness
  - profile: conda
    path: modules/msk/subworkflows/neoantigen_editing
  - profile: conda
    path: modules/msk/subworkflows/phylowgs
  - profile: conda
    path: modules/msk/netmhcstabpan
  - profile: conda
    path: modules/msk/ppflagfixer
  - profile: conda
    path: modules/msk/neoantigenutils/generatemutfasta
  - profile: conda
    path: modules/msk/neoantigenutils/formatnetmhcpan
  - profile: conda
    path: modules/msk/neoantigenutils/generatehlastring
  - profile: conda
    path: modules/msk/neoantigenutils/neoantigeninput
  - profile: conda
    path: modules/msk/subworkflows/netmhcstabandpan
  - profile: conda
    path: modules/msk/salmon/index
  - profile: conda
    path: modules/msk/genomenexus/vcf2maf
  - profile: conda
    path: modules/msk/genomenexus/annotationpipeline
  - profile: conda
    path: modules/msk/ppflagfixer
  - profile: conda
    path: modules/msk/pvmaf/tagtraceback
  - profile: conda
    path: modules/msk/pvmaf/concat
  - profile: conda
    path: modules/msk/genotypevariants/all
  - profile: conda
    path: modules/msk/subworkflows/traceback
  - profile: conda
    path: modules/msk/salmon/index
  - profile: conda
    path: modules/msk/subworkflows/genome_nexus
  - profile: conda
    path: modules/msk/salmon/quant
  - profile: conda
    path: modules/msk/rediscoverte
  - profile: conda
    path: modules/msk/neosv
  - profile: conda
    path: modules/msk/netmhc3
