---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "netmhcpan4"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "NETMHCPAN4"
