name: salmon_quant
description: gene/transcript quantification with Salmon
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - salmon:
      description: |
        Salmon is a tool for wicked-fast transcript quantification from RNA-seq data
      homepage: https://salmon.readthedocs.io/en/latest/salmon.html
      manual: https://salmon.readthedocs.io/en/latest/salmon.html
      doi: 10.1038/nmeth.4197
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files for single-end or paired-end data.
        Multiple single-end fastqs or pairs of paired-end fastqs are
        handled.
  - index:
      type: file
      description: The index file
output:
  - results:
      type: directory
      description: Folder containing the quantification results for a specific sample
      pattern: "${prefix}.salmon.quant"
  - quant:
      type: file
      description: File containing the sample quantification results
      pattern: "${meta.id}.quant.sf"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kevinmenden"
  - "@drpatelh"
maintainers:
  - "@kevinmenden"
  - "@drpatelh"
