---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "neoantigeninput"
description: This module take several inputs to the Lukza neoantigen pipeline and combines them into a single json file ready for input into their pipeline
keywords:
  - neoantigen
  - aggregate
  - genomics
tools:
  - neoantigeninput:
      description: "This module take several inputs to the Lukza neoantigen pipeline and combines them into a single json file ready for input into their pipeline"
      documentation: "https://github.com/LukszaLab/NeoantigenEditing"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.  Maybe cohort and patient_id as well?
        e.g. `[ id:'sample1', single_end:false ]`

  - inputMaf:
      type: file
      description: Maf outputtted by Tempo that was run through phyloWGS
      pattern: "*.{maf}"

  - phyloWGSsumm:
      type: file
      description: Summ json outputtted by phyloWGS
      pattern: "*.{json.gz}"

  - phyloWGSmut:
      type: file
      description: Summary json outputtted by phyloWGS
      pattern: "*.{json.gz}"

  - phyloWGSfolder:
      type: file
      description: Folder of mutations in trees output by PhyloWGS
      pattern: ".{zip}"

  - mutNetMHCpan:
      type: file
      description: STDOUT file of netMHCpan.  A poorly formated file of neoantigens.  This containes the mutated neoantigens
      pattern: "./"

  - wtNetMHCpan:
      type: file
      description: STDOUT file of netMHCpan.  A poorly formated file of neoantigens.  This containes the wild type antigens
      pattern: "./"

  - hlaFile:
      type: file
      description: HLA tsv outputtted by Polysolver
      pattern: "winners.{tsv}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - json:
      type: file
      description: output combined Json ready for input into the neoantigen pipeline
      pattern: "*.{json}"

  - netMHCpanreformatted_WT:
      type: file
      description: A reformatted file of neoantigens and their binding affinities output by netmhcpan.  This containes the wild type antigens
      pattern: "*.{WT.tsv}"

  - netMHCpanreformatted_WT:
      type: file
      description: A reformatted file of neoantigens and their binding affinities output by netmhcpan.  This containes the mutated antigens
      pattern: "*.{MUT.tsv}"

authors:
  - "@johnoooh"
maintainers:
  - "@johnoooh"
