name: "calculatenoise"
description: Performs noise calculation for ACCESSv2 standard BAM files
keywords:
  - calculate
  - noise
  - ACCESS
tools:
  - calculatenoise:
      description: "Performs noise calculation for ACCESSv2 standard BAM files"
      homepage: "https://github.com/msk-access/sequence_qc"
      documentation: "https://github.com/msk-access/sequence_qc"
      tool_dev_url: "https://github.com/msk-access/sequence_qc"
      doi: ""
      licence: ["MIT"]
      identifier: null

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: SAM/BAM/CRAM file
        pattern: "*.{sam,bam,cram}"
    - bai:
        type: file
        description: Optional SAM/BAM/CRAM file index
        pattern: "*.{sai,bai,crai}"
    - target_intervals:
        type: file
        description: An interval file that contains the locations of the targets.
        pattern: "*.{interval_list,bed,bed.gz}"
  - - fasta:
        type: file
        description: Input reference sequence file
        pattern: "*.fasta"
  - - fai:
        type: file
        description: Index of the reference Fasta
        pattern: "*.fai"

output:
  - acgt:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}_acgt.tsv:
          type: map
          description: noise metrics
          pattern: "*_acgt.tsv"
  - substitution:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_substitution.tsv":
          type: file
          description: noise metrics
          pattern: "*_substitution.tsv"
  - bytlen:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_by_tlen.tsv":
          type: file
          description: noise metrics
          pattern: "*_by_tlen.tsv"
  - del:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_del.tsv":
          type: file
          description: noise metrics
          pattern: "*_del.tsv"
  - count:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_n.tsv":
          type: file
          description: noise metrics
          pattern: "*_n.tsv"
  - positions:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_positions.tsv":
          type: file
          description: noise metrics
          pattern: "*_positions.tsv"
  - positions:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_positions.tsv":
          type: file
          description: noise metrics
          pattern: "*_positions.tsv"
  - html:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_noise.html":
          type: file
          description: noise metrics
          pattern: "*_noise.html"
  - pileup:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_pileup.tsv":
          type: file
          description: noise metrics
          pattern: "*_pileup.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mikefeixu"
maintainers:
  - "@mikefeixu"