---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
description: MuTect2 Variant Caller Module
keywords:
  - variant
  - caller
  - mutect2
tools:
  - "mutect2":
      description: "MuTect2 Variant Caller Module"
      homepage: "https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2"

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - case_bam:
        type: file
        description: Input Case Sample BAM file
        pattern: "*.{bam}"

    - control_bam:
        type: file
        description: Input Control Sample BAM file
        pattern: "*.{bam}"

    - case_bai:
        type: file
        description: Input Case Sample BAM index file
        pattern: "*.{bai}"

    - control_bai:
        type: file
        description: Input Control Sample BAM index file
        pattern: "*.{bai}"

    - bed_file:
        type: file
        description: Input Intervals File
        pattern: "*.{bed}"

    - fasta_file:
        type: file
        description: Input Reference Fasta File
        pattern: "*.{fasta}"

    - fasta_index_file:
        type: file
        description: Input Reference Fasta Index File
        pattern: "*.{fasta.fai}"

    - fasta_dict_file:
        type: file
        description: Input Reference Fasta Sequence Dictionary File
        pattern: "*.{dict}"

output:

      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`

      - "*.vcf":
          type: file
          description: Output VCF Variant Caller File 
          pattern: "*.{vcf}"
          ontologies:

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@rnaidu"
maintainers:
  - "@rnaidu"
