---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "phylowgs_parsecnvs"
description: parse cnvs from FACETS for input to phylowgs
keywords:
  - phylowgs
  - CNVs
  - FACETs
tools:
  - "phylowgs_parsecnvs":
      description: "parser to convert FACETs output to phylowgs expected input"
      homepage: "https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0602-8"
      tool_dev_url: "https://github.com/mskcc/phylowgs"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - facetsgenelevel:
      type: file
      description: single sample facets gene level output
      pattern: "*.{txt}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - cnv:
      type: file
      description: converted cnv file for phylowgs upstream processing
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@pintoa1-mskcc"
maintainers:
  - "@pintoa1-mskcc"
