---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "mutect1"

description: This module wraps MuTect v.1.1.5 software, which generates VCF files and standard output from case-control sample BAM files, BED file coordinates, and a reference fasta.
keywords:
  - vcf
  - case-control
  - bams
tools:
  - "mutect1":
      description: "Generates VCF file and standard output for case-control sample BAM files."
      homepage: "https://github.com/msk-access/mutect1"
      documentation: "https://github.com/msk-access/mutect1/blob/master/README.md"

input:
  # Only when we have meta
  - meta:
      type: map
      description: Groovy Map containing sample information e.g. `[ tumor_id:'tumor_sample', normal_id:'normal_sample' ]`

  - case_bam:
      type: file
      description: Case sample BAM file
      pattern: "*.{bam}"

  - control_bam:
      type: file
      description: Control sample BAM file
      pattern: "*.{bam}"

  - case_bai:
      type: file
      description: Case sample BAM index file
      pattern: "*.{bai}"

  - control_bai:
      type: file
      description: Control sample BAM index file
      pattern: "*.{bai}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - mutect_vcf:
      type: file
      description: |
        Output VCF file generated by MuTect v.1.1.5

  - standard_mutect_output:
      type: file
      description: |
        Output standard text file generated by MuTect v.1.1.5

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rnaidu"
maintainers:
  - "@rnaidu"
