# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "facets"
description:
  Algorithm to implement Fraction and Allele specific Copy number Estimate
  from Tumor/normal Sequencing.
keywords:
  - facets
  - pileup
  - Allele specific
  - Copy number
tools:
  - "facets-suite":
      description: "An R package with functions to run"
      homepage: "https://github.com/mskcc/facets-suite"
      documentation: "https://github.com/mskcc/facets-suite"
      licence: ["MIT"]
      identifier: biotools:facets
  - "facets":
      description:
        "Algorithm to implement Fraction and Allele specific Copy number
        Estimate from Tumor/normal Sequencing."
      homepage: "https://github.com/mskcc/facets"
      documentation: "https://github.com/mskcc/facets"
      doi: "10.1093/nar/gkw520"

      identifier: biotools:facets
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'pair_id' ]`
    - snp_pileup:
        type: file
        description: The pileup file
        pattern: "*.snp_pileup.gz"
    - legacy_output_mode:
        type: boolean
        description: Flag to run Facets in legacy output mode
output:
  - purity_seg:
      - meta:
          type: file
          description: The purity seg file
          pattern: "*_purity.seg"
      - "*_purity.seg":
          type: file
          description: The purity seg file
          pattern: "*_purity.seg"
  - purity_r_data:
      - meta: {}
      - "*_purity.?d*": {}
  - purity_png:
      - meta:
          type: file
          description: The purity png file. In legacy output the file would match *.CNCF.png
          pattern: "*_purity*png"
      - "*_purity*png":
          type: file
          description: The purity png file. In legacy output the file would match *.CNCF.png
          pattern: "*_purity*png"
  - purity_out:
      - meta:
          type: file
          description: The purity out file. Only in legacy output mode.
          pattern: "*_purity.out"
      - "*_purity.out":
          type: file
          description: The purity out file. Only in legacy output mode.
          pattern: "*_purity.out"
  - purity_cncf_txt:
      - meta:
          type: file
          description: The purity cncf file. Only in legacy output mode.
          pattern: "*_purity.cncf.txt"
      - "*_purity.cncf.txt":
          type: file
          description: The purity cncf file. Only in legacy output mode.
          pattern: "*_purity.cncf.txt"
  - hisens_seg:
      - meta:
          type: file
          description: The hisens seg file
          pattern: "*_hisens.seg"
      - "*_hisens.seg":
          type: file
          description: The hisens seg file
          pattern: "*_hisens.seg"
  - hisens_r_data:
      - meta: {}
      - "*_hisens.?d*": {}
  - hisens_png:
      - meta:
          type: file
          description: The hisens png file. In legacy output the file would match *.CNCF.png
          pattern: "*_hisens*png"
      - "*_hisens*png":
          type: file
          description: The hisens png file. In legacy output the file would match *.CNCF.png
          pattern: "*_hisens*png"
  - hisens_out:
      - meta:
          type: file
          description: The hisense out file. Only in legacy output mode.
          pattern: "*_hisens.out"
      - "*_hisens.out":
          type: file
          description: The hisense out file. Only in legacy output mode.
          pattern: "*_hisens.out"
  - hisens_cncf_txt:
      - meta:
          type: file
          description: The hisens cncf file. Only in legacy output mode.
          pattern: "*_hisens.cncf.txt"
      - "*_hisens.cncf.txt":
          type: file
          description: The hisens cncf file. Only in legacy output mode.
          pattern: "*_hisens.cncf.txt"
  - qc_txt:
      - meta:
          type: file
          description: The qc file
          pattern: "*.qc.txt"
      - "*.qc.txt":
          type: file
          description: The qc file
          pattern: "*.qc.txt"
  - gene_level_txt:
      - meta:
          type: file
          description: The gene level file
          pattern: "*.gene_level.txt"
      - "*.gene_level.txt":
          type: file
          description: The gene level file
          pattern: "*.gene_level.txt"
  - arm_level_txt:
      - meta:
          type: file
          description: The arm level file
          pattern: "*.arm_level.txt"
      - "*.arm_level.txt":
          type: file
          description: The arm level file
          pattern: "*.arm_level.txt"
  - output_txt:
      - meta:
          type: file
          description: The facets output log file. Format [id].txt
          pattern: "*.txt"
      - ${meta.id}.txt:
          type: file
          description: The facets output log file. Format [id].txt
          pattern: "*.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@nikhil"
maintainers:
  - "@nikhil"
