---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.jsonchannels:
channels:
  - conda-forge
  - bioconda
dependencies:
  - "YOUR-TOOL=HERE"
