---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pvmaf_concat"
description: a flexible command for concatenating maf files
keywords:
  - sort
  - example
  - genomics
tools:
  - "pvmaf":
      description: "provides a variety of commands for manipulating mafs."
      homepage: "https://github.com/msk-access/postprocessing_variant_calls"
      documentation: "https://cmo-ci.gitbook.io/postprocessing_variant_calls/"
      licence: ["MIT"]

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', patient:'patient1' ]`
  - maf_files:
      type: file
      description: list of maf files to concatenate
      pattern: "*.{maf}"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', patient:'patient1' ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - maf:
      type: file
      description: concatenated maf file
      pattern: "*.{maf}"

authors:
  - "@buehlere"
maintainers:
  - "@buehlere"
