name: "fgbio_collectduplexseqmetrics"
description: Collects a suite of metrics to QC duplex sequencing data.
keywords:
  - duplex
  - sequencing
  - genomics
  - fgbio
tools:
  - "fgbio":
      description: "A set of tools for working with genomic and high throughput sequencing data, including UMIs"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ["MIT"]
      identifier: biotools:fgbio

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: SAM/BAM/CRAM file
        pattern: "*.{sam,bam,cram}"

output:
  - family_sizes:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.family_sizes.txt:
          type: map
          description: Metrics on the frequency of different types of families of different sizes.
          pattern: "*.family_sizes.txt"
  - duplex_family_sizes:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.duplex_family_sizes.txt:
          type: file
          description: Metrics on the frequency of duplex tag families by the number of observations from each strand.
          pattern: "*.duplex_family_sizes.txt"
  - duplex_yield_metrics:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.duplex_yield_metrics.txt:
          type: file
          description: Summary QC metrics produced using 5%, 10%, 15%...100% of the data.
          pattern: "*.duplex_yield_metrics.txt"
  - umi_counts:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.umi_counts.txt:
          type: file
          description: Metrics on the frequency of observations of UMIs within reads and tag families.
          pattern: "*.umi_counts.txt"
  - duplex_umi_counts:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.duplex_umi_counts.txt:
          type: file
          description: Metrics on the frequency of observations of duplex UMIs within reads and tag families.
          pattern: "*.duplex_umi_counts.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mikefeixu"
maintainers:
  - "@mikefeixu"
