# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "neoantigenutils_generatemutfasta"
description: Generate the mutation fasta for netmhc tools
keywords:
  - neoantigen
  - fasta
  - netmhc
  - mutation
tools:
  - neoantigen_utils:
      description: "Collection of helper scripts for neoantigen processing"
      documentation: "https://github.com/mskcc-omics-workflows/modules"
      licence: [""]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information.
          e.g. `[ id:'sample1', single_end:false ]`
    - inputMaf:
        type: file
        description: Maf outputtted by Tempo that was run through phyloWGS
        pattern: "*.{maf}"
  - - cds:
        type: file
        description: coding sequence resource fasta
        pattern: "*.{cds.all.fa.gz}"
    - cdna:
        type: file
        description: cDNA resource fasta
        pattern: "*.{cdna.all.fa.gz}"
output:
  - mut_fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_out/*.MUT.sequences.fa":
          type: file
          description: Mutated fasta sequence
          pattern: "*.{MUT.sequences.fa}"
  - wt_fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_out/*.WT.sequences.fa":
          type: file
          description: Wildtype fasta sequence
          pattern: "*.{WT.sequences.fa}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@johnoooh"
  - "@nikhil"
maintainers:
  - "@johnoooh"
  - "@nikhil"
