# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "netmhcstabandpan"
description: Run netmhcpan and netmhcstabpan in parallel.
keywords:
  - peptides
  - netmhc
  - neoantigen
  - tsv
components:
  - neoantigenutils/generatehlastring
  - neoantigenutils/generatemutfasta
  - netmhcpan
  - netmhcstabpan
  - neoantigenutils/formatnetmhcpan
input:
  - ch_maf_and_hla:
      type: file
      description: |
        The input channel containing the maf and files
        Structure: [ val(meta), path(maf), path(hla) ]
      pattern: "*.{maf/txt}"
  - ch_cds_and_cdna:
      type: file
      description: |
        The resource channel containing the cds and cdna files
        Structure: [ path(cds) , path(cdna) ]
      pattern: "*.{fa.gz}"
output:
  - tsv:
      type: file
      description: |
        Channel containing TSV files
        Structure: [ val(meta), path(tsv) ]
      pattern: "*.tsv"
  - xls:
      type: file
      description: |
        Channel containing XLS files
        Structure: [ val(meta), path(xls) ]
      pattern: "*.xls"
  - mut_fasta:
      type: file
      description: |
        Channel containing the MUT fasta files
        Structure: [ val(meta), path(mut_fasta) ]
      pattern: "*.fa"
  - wt_fasta:
      type: file
      description: |
        Channel containing the WT fasta files
        Structure: [ val(meta), path(wt_fasta) ]
      pattern: "*.fa"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@nikhil"
maintainers:
  - "@nikhil"
