# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "ppflagfixer"
## TODO nf-core: Add a description of the module and list keywords
description: pplag-fixer for a single bam file
keywords:
  - ppflag
  - fixer
  - bams
tools:
  - "htstools":
      description: "Contains tools to process bam files for downstream copy number analysis."
      homepage: "https://github.com/mskcc/htstools"
      documentation: "https://github.com/mskcc/htstools"

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample_name' ]`
    - process_bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - process_bam_index:
        type: file
        description: "Index of the process bam file"
        pattern: "*.bai"
output:
  - ppflag_bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample_name' ]`
      - ppflag.*.bam:
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{bam,cram,sam}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@huyu335"
maintainers:
  - "@huyu335"
