name: "merge"
description: Merge a pair of raw fastq files from two different lanes
keywords:
  - merge
tools:
  - "gzip":
      description: "Files to compress or decompress"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: ""

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', sample_name:'Sample-T', read:'1' ]
  #
  ## TODO nf-core: Delete / customise this example input
  - fastq_1:
      type: file
      description: fastq file from Lane 1
      pattern: "*_L001_R*_001.fastq.gz"
  - fastq_2:
      type: file
      description: fastq file from Lane 2
      pattern: "*_L002_R*_001.fastq.gz"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', sample_name:'Sample-T', read:'1' ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - mrg_fq:
      type: file
      description: Merge fastq file
      pattern: "*_R*_mrg.fastq.gz"

authors:
  - "@huyu335"
