# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "polysolver"
description: HLA class I genotyping
keywords:
  - hla
  - genotyping
  - bam
tools:
  - "polysolver":
      description: "HLA typing"
      licence: ["GPL v3"]
      homepage: "https://software.broadinstitute.org/cancer/cga/polysolver"

      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bam:
        type: file
        description: Sorted BAM file
        pattern: "*.{bam,cram,sam}"
  - - includeFreq:
        type: integer
        description:
          "Flag indicating whether population-level allele frequencies should
          be used as priors (0 or 1) (Default: 1)"
  - - build:
        type: string
        description:
          "reference genome used in the BAM file (hg18 or hg19 or hg38) (Default:
          hg19)"
  - - format:
        type: string
        description:
          "fastq format (STDFQ, ILMFQ, ILM1.8 or SLXFQ; see Novoalign documentation)
          (Default: STDFQ)"
  - - insertCalc:
        type: integer
        description:
          "flag indicating whether empirical insert size distribution should
          be used in the model (0 or 1) (Default: 0)"
output:
  - hla:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.hla.txt":
          type: file
          description: Polysolver HLA genotyping result
          pattern: "*.hla.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@anoronh4"
maintainers:
  - "@anoronh4"
