name: Assign and Update Code Owners

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Run generate_codeowners.sh
        run: |
          chmod +x .github/generate_codeowners.sh
          ./.github/generate_codeowners.sh

      - name: Commit CODEOWNERS changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: '.github/CODEOWNERS'
          message: 'Update CODEOWNERS file'
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
