name: Assign and Update Code Owners

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Run generate_codeowners.sh
        run: |
          chmod +x .github/generate_codeowners.sh
          ./.github/generate_codeowners.sh

      - name: Commit CODEOWNERS changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .github/CODEOWNERS
          git commit -m "Update CODEOWNERS file" || echo "No changes to commit"
          git push
