name: Assign and Update Code Owners

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install yq
        run: |
          sudo snap install yq
          sudo apt install fd-find
      - name: Run generate_codeowners.sh
        run: |
          chmod +x .github/generate_codeowners.sh
          ./.github/generate_codeowners.sh
      - name: Validate codeowners file
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
      - name: Commit CODEOWNERS changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '[".github/CODEOWNERS --force"]'
          message: "Update CODEOWNERS file"
          default_author: github_actions
          cwd: "./"
