---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "genomenexus_annotationpipeline"

description: DSL2 module to annotate a MAF file type using the genomenexus suite of conversion and annotation tools.
keywords:
  - sort
  - example
  - genomics
tools:
  - "genomenexus":
      
      description: "DSL2 module to annotate a MAF file type using the genomenexus suite of conversion and annotation tools."
      homepage: "https://github.com/genome-nexus/genome-nexus-annotation-pipeline"
      documentation: "https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/README.md"
      licence:

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`

  - input_maf:
      type: file
      description: input MAF file
      pattern: "*.{maf}"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - maf:
      type: file
      description: output MAF file
      pattern: "*.{maf}"

authors:
  - "@rnaidu"
maintainers:
  - "@rnaidu"
